import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useForm } from 'react-hook-form';

import { useEtherBalance, useEthers, Config } from '@usedapp/core';

import { formatEther } from '@ethersproject/units';

export const Input = ({ label, name, register, required, placeholder }) => {
  return (
    <div className="flex flex-col gap-3">
      <label
        htmlFor="email"
        className="block text-sm font-medium text-gray-700"
      >
        {label}
      </label>
      <div className="mt-1">
        <input
          type="text"
          {...register(name, { required })}
          className="text-2xl focus:ring-indigo-500 focus:border-indigo-500 block w-full  border-transparent rounded-md"
          placeholder={placeholder}
        />
      </div>
    </div>
  );
};

export const Select = React.forwardRef(
  ({ onChange, onBlur, name, label }, ref) => (
    <div className="flex flex-col gap-3">
      <label>{label}</label>
      <select name={name} ref={ref} onChange={onChange} onBlur={onBlur}>
        <option value="20">20</option>
        <option value="30">30</option>
      </select>
    </div>
  )
);
Select.displayName = 'Select';

export const CardSelect = ({ label }) => {
  const people = [1, 2];
  return (
    <div className="flex flex-col gap-3">
      <label
        htmlFor="email"
        className="block text-sm font-medium text-gray-700"
      >
        {label}
      </label>
      <ul role="list" className="grid grid-cols-1 gap-8 grid-cols-2 ">
        {people.map(person => (
          <li
            key={person.email}
            className="w-[150px] col-span-1 grid grid-cols-2 bg-white rounded-lg shadow divide-y divide-x divide-gray-200 cursor-pointer "
          >
            <div className="w-[75px] h-[75px]  flex items-center justify-between p-6 space-x-6 aspect-square pb-full">
              1
            </div>
            <div className="aspect-square w-[75px] h-[75px] flex items-center justify-between p-6 space-x-6">
              2
            </div>
            <div className="aspect-square w-[75px] h-[75px] flex items-center justify-between p-6 space-x-6">
              3
            </div>
            <div className="w-[75px] h-[75px] flex items-center justify-between p-6 space-x-6">
              4
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
};

const Connect = () => {
  const { activateBrowserWallet, account } = useEthers();

  const etherBalance = useEtherBalance(account);

  return (
    <div>
      {!account && (
        <button onClick={() => activateBrowserWallet()}>Connect</button>
      )}
      {account && <p>Account: {account}</p>}
      {etherBalance && <p>Balance: {formatEther(etherBalance)}</p>}
    </div>
  );
};

export default function Home() {
  const { register, handleSubmit } = useForm();
  const onSubmit = data => {
    alert(JSON.stringify(data));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Connect />
      <main className={styles.main}>
        <div className="flex justify-between gap-10 w-full max-w-2xl">
          <div>
            <form
              onSubmit={handleSubmit(onSubmit)}
              className="flex flex-col gap-y-8"
            >
              <Input
                name="communityName"
                label="Community Name"
                placeholder="DAOschool"
                register={register}
              />
              <CardSelect label={'Head Collections'} />
              <CardSelect label={'Body Collections'} />
            </form>
          </div>

          <div>
            <h2>Preview</h2>
            <div className="w-[300px] h-[300px] flex justify-center items-center bg-white rounded-lg shadow divide-y divide-x divide-gray-200 cursor-pointer">
              image
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
